name: Sandstone Grillhouse
favicon: null
layout_spectrum: 0.062116459710523486
typography_spectrum: 0.05231930059380829
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8254860967863351
  lightness: 0.1061818019952625
  saturation: 0.2865399168804288
  rhythmicContrast: 0.7839059652760625
purpose: []
