name: Sandstone Grillhouse
favicon: null
layout_spectrum: 0.19818
typography_spectrum: 1
title: Sandstone Grillhouse
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0b'
    - '#423427'
    - '#81653d'
    - '#fdfeff'
    - '#e2cb7f'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
