name: Sandstone Grillhouse
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40096
title: Sandstone Grillhouse
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#220000'
    - '#806a76'
    - '#990002'
    - '#eee8dc'
    - '#e4a15d'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
